name: ci-test

on:
  push:
    branches:
      - 'main'
      - 'feature-**'
      - 'bugfix-**'
      - 'hotfix-**'
  pull_request:
    branches:
      - 'main'
      - 'feature-**'
      - 'bugfix-**'
      - 'hotfix-**'

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.18 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Clear cache
      run: go clean -testcache
    - name: Run test
      run: go test ./... -v --failfast